apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: gurnxr/stgi:latest  # Replace with your actual Docker image
        ports:
        - containerPort: 8000
        command: ["./prod_start.sh"]
        volumeMounts:
        - name: web-code
          mountPath: /code
        envFrom:
        - configMapRef:
            name: web-env-config
      volumes:
      - name: web-code
        hostPath:
          path: C:\Users\gurno\Desktop\hack\PyEditorial   # Adjust this path
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP  # Use LoadBalancer if you want external access
